# Generated by Django 4.2.1 on 2023-05-31 07:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombreCategoria', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='nombre de la categoria')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
                ('fechaPedido', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombreMarca', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='nombre Marca')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('nombreSubCategoria', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre subcategoria')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('slugcat', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': 'sub categories',
            },
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('nombreTipoInstrumento', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='nombre tipo instrumento')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=10)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(null=True, upload_to='img/productos')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_available', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
                ('tipoinstrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoinstrumento')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('username', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, null=True, verbose_name='apellido')),
                ('telefono', models.CharField(max_length=255, null=True, verbose_name='telefono')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_bodeguero', models.BooleanField(default=False)),
                ('is_vendedor', models.BooleanField(default=False)),
                ('is_contador', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
