# Generated by Django 4.2.1 on 2023-05-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('marca', models.CharField(max_length=10, verbose_name='marca')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
    ]
