# Generated by Django 4.2.1 on 2023-05-27 19:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='slugcat',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='categoria'),
        ),
    ]
