# Generated by Django 4.2.1 on 2023-06-28 16:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='slugcat',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreCategoria'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreMarca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreProducto'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreSubCategoria'),
        ),
        migrations.AlterField(
            model_name='tipoinstrumento',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreTipoInstrumento'),
        ),
    ]
