# Generated by Django 4.1.4 on 2023-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='marca')),
                ('marca', models.CharField(max_length=50, verbose_name='nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreSubCategoria', models.CharField(max_length=50, verbose_name='nombre subcategoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
