# Generated by Django 4.2 on 2023-05-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='tipoPago',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='user',
        ),
        migrations.DeleteModel(
            name='Detalle_orden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
