# Generated by Django 4.1.4 on 2023-05-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marca_subcategoria_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('Subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
        ),
    ]
