# Generated by Django 4.2.1 on 2023-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
                ('fechaPago', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
