# Generated by Django 4.2.1 on 2023-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_invitado_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitado',
            old_name='fechaPago',
            new_name='fechaPedido',
        ),
    ]
