# Generated by Django 4.2.1 on 2023-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=100),
        ),
    ]
