# Generated by Django 4.2 on 2023-05-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(choices=[('PU', 'Retiro en tienda'), ('DE', 'Entrega a domicilio')], default='PU', max_length=2)),
            ],
        ),
    ]
