# Generated by Django 4.2 on 2023-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
