# Generated by Django 4.2.1 on 2023-05-14 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_fechapago_invitado_fechapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
