# Generated by Django 4.2.1 on 2023-05-14 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 15, 32, 27, 468692)),
        ),
    ]
