# Generated by Django 4.2.1 on 2023-05-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_marca_slug'),
        ('app', '0006_delete_order'),
    ]

    operations = [
    ]
