# Generated by Django 4.2 on 2023-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0005_alter_marca_slug_0006_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
