# Generated by Django 4.2.1 on 2023-05-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0005_alter_marca_slug_0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=10)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
        ),
    ]
