# Generated by Django 4.2 on 2023-05-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_marca_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=10)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
        ),
    ]
