# Generated by Django 4.2 on 2023-05-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categoria_marca_subcategoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Subcategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
