# Generated by Django 4.2.1 on 2023-05-30 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_region_alter_marca_slug_sucursal_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('nombrePago', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=80, null=True)),
                ('total', models.IntegerField()),
                ('tax', models.IntegerField(null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal')),
                ('tipoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipopago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('numero_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
