# Generated by Django 4.2 on 2023-05-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_producto_subcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=50, unique=True, verbose_name='nombre de la categoria')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=50, unique=True, verbose_name='nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubCategoria', models.CharField(max_length=50, verbose_name='nombre subcategoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': 'sub categories',
            },
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubCategoria', models.CharField(max_length=50, verbose_name='nombre subcategoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': 'sub categories',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='img/productos')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_avaliable', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('TipoInstrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoinstrumento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
        ),
    ]
