# Generated by Django 4.2.1 on 2023-05-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comuna_region_alter_sucursal_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(max_length=222, primary_key=True, serialize=False),
        ),
    ]
