# Generated by Django 4.2 on 2023-05-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categoria_marca_subcategoria_tipoinstrumento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoinstrumento',
            old_name='nombreSubCategoria',
            new_name='nombreTipoInstrumento',
        ),
    ]
