# Generated by Django 4.2 on 2023-05-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_nombresubcategoria_tipoinstrumento_nombretipoinstrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='TipoInstrumento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tipoinstrumento',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
        migrations.DeleteModel(
            name='TipoInstrumento',
        ),
    ]
