# Generated by Django 4.2 on 2023-05-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_producto_tipoinstrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='TipoInstrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoinstrumento'),
        ),
    ]
