# Generated by Django 4.2 on 2023-05-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_categoria_marca_subcategoria_tipoinstrumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='SubCategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='TipoInstrumento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
