# Generated by Django 4.2 on 2023-05-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=50, unique=True, verbose_name='nombre Marca')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='nombre')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='img/productos')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_available', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('SubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategoria')),
                ('TipoInstrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoinstrumento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
        ),
    ]
