# Generated by Django 4.2 on 2023-05-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_marca_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
