# Generated by Django 4.2 on 2023-05-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='SubCategoria',
            new_name='subcategoria',
        ),
    ]
