# Generated by Django 4.2 on 2023-05-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='TipoInstrumento',
            new_name='tipoinstrumento',
        ),
    ]
