# Generated by Django 4.2.1 on 2023-06-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_producto_alter_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ubicacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
